n1 = input('digite um numero: ')
print(type(n1))

n2 = int(input('digite outro numero: '))
n3 = int(input('digite mais um numero: '))
print(type(n2), type(n3))

print('a soma entre {} e {} é {}'.format(n2, n3, n2+n3))

n5 = input('Digite algo: ')
print(n5.isnumeric())
print('acima esta conferindo se o {} é numerico'.format(n5))
print(n5.isalpha())
print('acima esta conferindo se o {} é string'.format(n5))
print(n5.isalnum())
print('acima esta conferindo se o {} é numerico e string'.format(n5))
print(n5.istitle())
print('acima esta conferindo se o {} é um title'.format(n5))
print(n5.isascii())
print('acima esta conferindo se o {} é ascii'.format(n5))
print(n5.isdecimal())
print('acima esta conferindo se o {} é decimal'.format(n5))
print(n5.isdigit())
print('acima esta conferindo se o {} é digit'.format(n5))
print(n5.isidentifier())
print('Juro que não sei o que seria identifier')
print(n5.islower())
print('acima esta conferindo se o {} esta com todas as letras minusculas'.format(n5))
print(n5.isprintable())
print('eu juro que nao sei o que é printable')
print(n5.isspace())
print('serio o que é space, coferir se tem espaço? ')
print(n5.isupper())
print('acima esta conferindo se o {} esta com todas as letras maiuscula'.format(n5))